Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "master"
  config.vm.network "private_network", ip: "192.168.56.10"

  # Provisiona com o script
  config.vm.provision "shell", path: "provision.sh"
end
